app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
  resource: '.'
  type:     'api_platform'
  prefix: '/'

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

upload_picture:
  path: '/upload/{name}'
  methods: ['POST']
  defaults:
    _controller: 'AppBundle:Logo:upload'

#upload_file:
#  path:       '/upload/{name}'
#  controller: 'AppBundle:Picture:upload'
#  methods:    ['POST']

#api_login_check:
#    path: /api/login_check